version: "3.9"
services:
  ELASTICSEARCH_HOSTS:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elastic-curso-rapido
    environment:
      - node.name=elastic-curso-rapido
      - cluster.name=elastic-curso-rapido-cluster
      - discovery.seed_hosts=elastic-curso-rapido
      - cluster.initial_master_nodes=elastic-curso-rapido
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic-curso-rapido

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elastic-curso-rapido:9200
      ELASTICSEARCH_HOSTS: http://elastic-curso-rapido:9200
    networks:
      - elastic-curso-rapido

volumes:
  es_data:
    driver: local

networks:
  elastic-curso-rapido:
    driver: bridge